spring:
  application:
    name: spring-ai-rag
  #Pass API Key as environment variable, e.g. -DOPENAI_API_KEY=your-api-key
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
sfg:
  aiapp:
    vectorStorePath: /home/tdoyle/temp_vector_store/vectorstore.json
    documentsToLoad:
      - classpath:/movies500.csv
